const colors = {
    light: {
        text: "#0a0a0a",
        tint: "#C6F135",
        background: "#F5F5F5",
        foreground: "#0a0a0a",
        card: "#FFFFFF",
        cardForeground: "#0a0a0a",
        primary: "#C6F135",
        primaryForeground: "#0D0D0D",
        secondary: "#E8E8E8",
        secondaryForeground: "#1a1a1a",
        muted: "#E8E8E8",
        mutedForeground: "#737373",
        accent: "#C6F135",
        accentForeground: "#0D0D0D",
        destructive: "#EF4444",
        destructiveForeground: "#FFFFFF",
        border: "#E0E0E0",
        input: "#E0E0E0",
        semGreen: "#22C55E",
        semYellow: "#EAB308",
        semRed: "#EF4444",
    },
    dark: {
        text: "#FFFFFF",
        tint: "#C6F135",
        background: "#0D0D0D",
        foreground: "#FFFFFF",
        card: "#1A1A1A",
        cardForeground: "#FFFFFF",
        primary: "#C6F135",
        primaryForeground: "#0D0D0D",
        secondary: "#2A2A2A",
        secondaryForeground: "#FFFFFF",
        muted: "#2A2A2A",
        mutedForeground: "#888888",
        accent: "#C6F135",
        accentForeground: "#0D0D0D",
        destructive: "#EF4444",
        destructiveForeground: "#FFFFFF",
        border: "#2E2E2E",
        input: "#2E2E2E",
        semGreen: "#22C55E",
        semYellow: "#EAB308",
        semRed: "#EF4444",
    },
    radius: 14,
};
export default colors;
